# Generated by Django 3.2 on 2021-04-12 18:55

from django.db import migrations, models
import django.db.models.deletion
import opravy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Název')),
                ('znacka', models.CharField(blank=True, choices=[('apple', 'Apple'), ('samsung', 'Samsung'), ('huawei', 'Huawei'), ('xiaomi', 'Xiaomi')], default='apple', max_length=20, verbose_name='Výrobce')),
                ('cena', models.IntegerField(blank=True, null=True, verbose_name='Cena')),
            ],
            options={
                'ordering': ['znacka'],
            },
        ),
        migrations.CreateModel(
            name='Opravar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, verbose_name='Jmeno opraváře')),
                ('zamereni', models.CharField(blank=True, choices=[('apple', 'Apple'), ('samsung', 'Samsung'), ('huawei', 'Huawei'), ('xiaomi', 'Xiaomi')], default='apple', help_text='Zadejte značku jednoho z výrobcu mobilů, které opravujete', max_length=20, verbose_name='Zaměření')),
                ('bydliste', models.CharField(max_length=200, verbose_name='Bydliště')),
                ('vyplata', models.IntegerField(blank=True, verbose_name='Výplata')),
                ('foto', models.ImageField(blank=True, null=True, upload_to=opravy.models.opravar_path, verbose_name='Fotka')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Oprava',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popis', models.TextField(blank=True, verbose_name='Popis zavady')),
                ('cena', models.IntegerField(blank=True, verbose_name='Cena opravy')),
                ('time', models.DateTimeField(auto_now=True)),
                ('zakaznik', models.CharField(blank=True, max_length=200, null=True, verbose_name='Jméno a přijmení zákazníka')),
                ('foto', models.ImageField(blank=True, null=True, upload_to=opravy.models.oprava_path, verbose_name='Fotka')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opravy.model')),
                ('opravar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opravy.opravar')),
            ],
            options={
                'ordering': ['opravar'],
            },
        ),
    ]
