# Generated by Django 3.2 on 2021-05-11 16:51

from django.db import migrations, models
import opravy.models


class Migration(migrations.Migration):

    dependencies = [
        ('opravy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='fotka',
            field=models.ImageField(blank=True, null=True, upload_to=opravy.models.model_path, verbose_name='Fotka'),
        ),
    ]
