# Generated by Django 3.2 on 2021-05-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opravy', '0002_model_fotka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='znacka',
            field=models.CharField(blank=True, choices=[('apple', 'Apple'), ('samsung', 'Samsung'), ('huawei', 'Huawei'), ('xiaomi', 'Xiaomi')], default='Apple', max_length=20, verbose_name='Výrobce'),
        ),
    ]
