# Generated by Django 3.2 on 2021-05-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opravy', '0003_alter_model_znacka'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='cena',
        ),
        migrations.AddField(
            model_name='model',
            name='cena_baterka',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cena výměneny baterky'),
        ),
        migrations.AddField(
            model_name='model',
            name='cena_displej',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cena výměneny displeje'),
        ),
        migrations.AddField(
            model_name='model',
            name='cena_stav_a',
            field=models.IntegerField(blank=True, null=True, verbose_name='Výkupní cena stav A'),
        ),
        migrations.AddField(
            model_name='model',
            name='popis',
            field=models.TextField(blank=True, verbose_name='Popis produktu'),
        ),
    ]
