# Generated by Django 3.2 on 2021-05-18 14:58

from django.db import migrations, models
import django.db.models.deletion
import opravy.models


class Migration(migrations.Migration):

    dependencies = [
        ('opravy', '0004_auto_20210512_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Název')),
                ('foto', models.ImageField(blank=True, null=True, upload_to=opravy.models.brand_path, verbose_name='Fotka')),
            ],
            options={
                'ordering': ['opravar'],
            },
        ),
        migrations.RemoveField(
            model_name='opravar',
            name='bydliste',
        ),
        migrations.RemoveField(
            model_name='opravar',
            name='vyplata',
        ),
        migrations.AlterField(
            model_name='model',
            name='znacka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opravy.brand'),
        ),
        migrations.AlterField(
            model_name='opravar',
            name='zamereni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opravy.brand'),
        ),
    ]
