# Generated by Django 3.2 on 2021-05-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opravy', '0005_auto_20210518_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='oprava',
            name='time',
        ),
        migrations.AlterField(
            model_name='opravar',
            name='zamereni',
            field=models.CharField(blank=True, choices=[('apple', 'Apple'), ('samsung', 'Samsung'), ('huawei', 'Huawei'), ('xiaomi', 'Xiaomi')], default='apple', help_text='Zadejte značku jednoho z výrobcu mobilů, které opravujete', max_length=20, verbose_name='Zaměření'),
        ),
    ]
