# Generated by Django 3.2 on 2021-05-18 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opravy', '0006_auto_20210518_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oprava',
            name='model',
        ),
    ]
